#include <linux/ioctl.h>

#define IOC_MAGIC 'k'
#define IOCTL_ALTMINIX_CREATE_SNAPSHOT _IOR(IOC_MAGIC, 0, char*)
#define IOCTL_ALTMINIX_ROLLBACK_SNAPSHOT _IOR(IOC_MAGIC, 1, char*)
#define IOCTL_ALTMINIX_REMOVE_SNAPSHOT _IOR(IOC_MAGIC, 2, char*)

#define IOCTL_ERROR_SNAPSHOT_EXISTS			-1
#define IOCTL_ERROR_SNAPSHOT_DOES_NOT_EXIST	-2
#define IOCTL_ERROR_NO_FREE_SNAPSHOTS		-3